### PR TITLE
Deploy pyass automatically

### PR DESCRIPTION
**Pull request by Luni-4**
@rr- 

You need to set the same token process used for `pyffms2` and `pympv2`

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by rr-** [comment]
First we'll need to have published pyass on pypi, otherwise I can't add this token. Can I ask you to create that package?

**Comment by Luni-4** [comment]
> First we'll need to have published pyass on pypi, otherwise I can't add this token. Can I ask you to create that package?

Sincerely I don't think I'm the right person to create and maintain this package. If it is a problem for you, we can use this repository without uploading the package on `PyPI`
And I don't have a problem to replace my name as an author with yours, if you want. Feel free to do whatever you want :smile:

**Comment by rr-** [comment]
>we can use this repository without uploading the package on PyPI

Let's do it like this for a while and see what happens

**Comment by Luni-4** [comment]
I propose to merge this PR and don't release a new version

**Comment by rr-** [comment]
Cool :+1:

**Pull request merged**
